import { UserRole } from '@model-trainer/db';

export type PermissionCode =
  | 'USER_READ' | 'USER_CREATE' | 'USER_UPDATE' | 'USER_DISABLE'
  | 'USER_ENABLE' | 'USER_UNLOCK' | 'USER_RESET_PASSWORD' | 'USER_CHANGE_ROLE'
  | 'DATASET_READ' | 'DATASET_CREATE' | 'DATASET_UPDATE' | 'DATASET_ARCHIVE'
  | 'MODEL_READ' | 'MODEL_CREATE' | 'MODEL_ARCHIVE'
  | 'TRAINING_READ_OWN' | 'TRAINING_READ_ALL' | 'TRAINING_CREATE'
  | 'TRAINING_UPDATE_OWN' | 'TRAINING_CONTROL_OWN' | 'TRAINING_CONTROL_ALL'
  | 'BENCHMARK_READ_OWN' | 'BENCHMARK_READ_ALL' | 'BENCHMARK_CREATE'
  | 'BENCHMARK_CONTROL_OWN' | 'BENCHMARK_CONTROL_ALL'
  | 'ARTIFACT_READ'
  | 'AUDIT_READ_RESOURCE' | 'AUDIT_READ_GLOBAL'
  | 'NOTIFICATION_READ_OWN'
  | 'DATASET_TYPE_MANAGE'
  | 'WORKER_MANAGE' | 'SYSTEM_SETTING_MANAGE';

export const ROLE_PERMISSIONS: Record<UserRole, readonly PermissionCode[]> = {
  ADMIN: [
    'USER_READ', 'USER_CREATE', 'USER_UPDATE', 'USER_DISABLE',
    'USER_ENABLE', 'USER_UNLOCK', 'USER_RESET_PASSWORD', 'USER_CHANGE_ROLE',
    'DATASET_READ', 'DATASET_CREATE', 'DATASET_UPDATE', 'DATASET_ARCHIVE',
    'MODEL_READ', 'MODEL_CREATE', 'MODEL_ARCHIVE',
    'TRAINING_READ_OWN', 'TRAINING_READ_ALL', 'TRAINING_CREATE',
    'TRAINING_UPDATE_OWN', 'TRAINING_CONTROL_OWN', 'TRAINING_CONTROL_ALL',
    'BENCHMARK_READ_OWN', 'BENCHMARK_READ_ALL', 'BENCHMARK_CREATE',
    'BENCHMARK_CONTROL_OWN', 'BENCHMARK_CONTROL_ALL',
    'ARTIFACT_READ',
    'AUDIT_READ_RESOURCE', 'AUDIT_READ_GLOBAL',
    'NOTIFICATION_READ_OWN',
    'DATASET_TYPE_MANAGE',
    'WORKER_MANAGE', 'SYSTEM_SETTING_MANAGE',
  ],
  USER: [
    'DATASET_READ', 'DATASET_CREATE', 'DATASET_UPDATE',
    'MODEL_READ', 'MODEL_CREATE',
    'TRAINING_READ_OWN', 'TRAINING_CREATE',
    'TRAINING_UPDATE_OWN', 'TRAINING_CONTROL_OWN',
    'BENCHMARK_READ_OWN', 'BENCHMARK_CREATE',
    'BENCHMARK_CONTROL_OWN',
    'ARTIFACT_READ',
    'AUDIT_READ_RESOURCE',
    'NOTIFICATION_READ_OWN',
  ],
};
