// GENERATED by scripts/gen-yolo-args.mjs — do not edit by hand.
// Source of truth is the Ultralytics install in the training worker; re-run the script
// after upgrading Ultralytics, or the UI will accept arguments the worker rejects.
//
// kind:
//   bool      CFG_BOOL_KEYS
//   int       CFG_INT_KEYS
//   fraction  CFG_FRACTION_KEYS — numeric, 0..1
//   float     CFG_FLOAT_KEYS
//   other     strings/paths/nullable — only the key name is checked

export interface YoloArgSpec {
  kind: 'bool' | 'int' | 'fraction' | 'float' | 'other';
  default: string | number | boolean | null;
}

export const ULTRALYTICS_VERSION = "8.4.106";

export const YOLO_ARGS: Record<string, YoloArgSpec> = {
  "agnostic_nms": {
    "default": false,
    "kind": "bool"
  },
  "amp": {
    "default": true,
    "kind": "other"
  },
  "angle": {
    "default": 1,
    "kind": "float"
  },
  "augment": {
    "default": false,
    "kind": "bool"
  },
  "auto_augment": {
    "default": "randaugment",
    "kind": "other"
  },
  "batch": {
    "default": 16,
    "kind": "float"
  },
  "bgr": {
    "default": 0,
    "kind": "fraction"
  },
  "box": {
    "default": 7.5,
    "kind": "float"
  },
  "cache": {
    "default": false,
    "kind": "other"
  },
  "cfg": {
    "default": null,
    "kind": "other"
  },
  "channels_last": {
    "default": false,
    "kind": "bool"
  },
  "classes": {
    "default": null,
    "kind": "other"
  },
  "close_mosaic": {
    "default": 10,
    "kind": "int"
  },
  "cls": {
    "default": 0.5,
    "kind": "float"
  },
  "cls_pw": {
    "default": 0,
    "kind": "fraction"
  },
  "cls_remap": {
    "default": true,
    "kind": "bool"
  },
  "compile": {
    "default": false,
    "kind": "other"
  },
  "conf": {
    "default": null,
    "kind": "fraction"
  },
  "copy_paste": {
    "default": 0,
    "kind": "fraction"
  },
  "copy_paste_mode": {
    "default": "flip",
    "kind": "other"
  },
  "cos_lr": {
    "default": false,
    "kind": "bool"
  },
  "cutmix": {
    "default": 0,
    "kind": "fraction"
  },
  "data": {
    "default": null,
    "kind": "other"
  },
  "degrees": {
    "default": 0,
    "kind": "float"
  },
  "deterministic": {
    "default": true,
    "kind": "bool"
  },
  "device": {
    "default": null,
    "kind": "other"
  },
  "dfl": {
    "default": 1.5,
    "kind": "float"
  },
  "dgrad": {
    "default": 0.5,
    "kind": "float"
  },
  "dis": {
    "default": 6,
    "kind": "float"
  },
  "distill_model": {
    "default": null,
    "kind": "other"
  },
  "dlam": {
    "default": 1,
    "kind": "fraction"
  },
  "dlog": {
    "default": 1,
    "kind": "float"
  },
  "dnn": {
    "default": false,
    "kind": "bool"
  },
  "dropout": {
    "default": 0,
    "kind": "fraction"
  },
  "dynamic": {
    "default": false,
    "kind": "bool"
  },
  "embed": {
    "default": null,
    "kind": "other"
  },
  "end2end": {
    "default": null,
    "kind": "bool"
  },
  "epochs": {
    "default": 100,
    "kind": "int"
  },
  "erasing": {
    "default": 0.4,
    "kind": "fraction"
  },
  "exist_ok": {
    "default": false,
    "kind": "bool"
  },
  "fliplr": {
    "default": 0.5,
    "kind": "fraction"
  },
  "flipud": {
    "default": 0,
    "kind": "fraction"
  },
  "format": {
    "default": "torchscript",
    "kind": "other"
  },
  "fraction": {
    "default": 1,
    "kind": "fraction"
  },
  "freeze": {
    "default": null,
    "kind": "other"
  },
  "hsv_h": {
    "default": 0.015,
    "kind": "fraction"
  },
  "hsv_s": {
    "default": 0.7,
    "kind": "fraction"
  },
  "hsv_v": {
    "default": 0.4,
    "kind": "fraction"
  },
  "imgsz": {
    "default": 640,
    "kind": "other"
  },
  "iou": {
    "default": 0.7,
    "kind": "fraction"
  },
  "keras": {
    "default": false,
    "kind": "bool"
  },
  "kobj": {
    "default": 1,
    "kind": "float"
  },
  "line_width": {
    "default": null,
    "kind": "int"
  },
  "lr0": {
    "default": 0.01,
    "kind": "fraction"
  },
  "lrf": {
    "default": 0.01,
    "kind": "fraction"
  },
  "mask_ratio": {
    "default": 4,
    "kind": "int"
  },
  "max_det": {
    "default": 300,
    "kind": "int"
  },
  "mixup": {
    "default": 0,
    "kind": "fraction"
  },
  "mode": {
    "default": "train",
    "kind": "other"
  },
  "model": {
    "default": null,
    "kind": "other"
  },
  "momentum": {
    "default": 0.937,
    "kind": "fraction"
  },
  "mosaic": {
    "default": 1,
    "kind": "fraction"
  },
  "multi_scale": {
    "default": 0,
    "kind": "fraction"
  },
  "name": {
    "default": null,
    "kind": "other"
  },
  "nbs": {
    "default": 64,
    "kind": "int"
  },
  "nms": {
    "default": false,
    "kind": "bool"
  },
  "opset": {
    "default": null,
    "kind": "other"
  },
  "optimize": {
    "default": false,
    "kind": "bool"
  },
  "optimizer": {
    "default": "auto",
    "kind": "other"
  },
  "overlap_mask": {
    "default": true,
    "kind": "bool"
  },
  "patience": {
    "default": 100,
    "kind": "int"
  },
  "perspective": {
    "default": 0,
    "kind": "fraction"
  },
  "plots": {
    "default": true,
    "kind": "bool"
  },
  "pose": {
    "default": 12,
    "kind": "float"
  },
  "pretrained": {
    "default": true,
    "kind": "other"
  },
  "profile": {
    "default": false,
    "kind": "bool"
  },
  "project": {
    "default": null,
    "kind": "other"
  },
  "quantize": {
    "default": null,
    "kind": "other"
  },
  "rect": {
    "default": false,
    "kind": "bool"
  },
  "resume": {
    "default": false,
    "kind": "other"
  },
  "retina_masks": {
    "default": false,
    "kind": "bool"
  },
  "rle": {
    "default": 1,
    "kind": "float"
  },
  "save": {
    "default": true,
    "kind": "bool"
  },
  "save_conf": {
    "default": false,
    "kind": "bool"
  },
  "save_crop": {
    "default": false,
    "kind": "bool"
  },
  "save_frames": {
    "default": false,
    "kind": "bool"
  },
  "save_json": {
    "default": false,
    "kind": "bool"
  },
  "save_period": {
    "default": -1,
    "kind": "int"
  },
  "save_txt": {
    "default": false,
    "kind": "bool"
  },
  "scale": {
    "default": 0.5,
    "kind": "other"
  },
  "seed": {
    "default": 0,
    "kind": "int"
  },
  "shear": {
    "default": 0,
    "kind": "float"
  },
  "show": {
    "default": false,
    "kind": "bool"
  },
  "show_boxes": {
    "default": true,
    "kind": "bool"
  },
  "show_conf": {
    "default": true,
    "kind": "bool"
  },
  "show_labels": {
    "default": true,
    "kind": "bool"
  },
  "simplify": {
    "default": true,
    "kind": "bool"
  },
  "single_cls": {
    "default": false,
    "kind": "bool"
  },
  "source": {
    "default": null,
    "kind": "other"
  },
  "split": {
    "default": "val",
    "kind": "other"
  },
  "stream_buffer": {
    "default": false,
    "kind": "other"
  },
  "task": {
    "default": "detect",
    "kind": "other"
  },
  "time": {
    "default": null,
    "kind": "float"
  },
  "tracker": {
    "default": "tracktrack.yaml",
    "kind": "other"
  },
  "translate": {
    "default": 0.1,
    "kind": "fraction"
  },
  "val": {
    "default": true,
    "kind": "bool"
  },
  "verbose": {
    "default": true,
    "kind": "bool"
  },
  "vid_stride": {
    "default": 1,
    "kind": "int"
  },
  "visualize": {
    "default": false,
    "kind": "bool"
  },
  "warmup_bias_lr": {
    "default": 0.1,
    "kind": "fraction"
  },
  "warmup_epochs": {
    "default": 3,
    "kind": "float"
  },
  "warmup_momentum": {
    "default": 0.8,
    "kind": "fraction"
  },
  "weight_decay": {
    "default": 0.0005,
    "kind": "fraction"
  },
  "workers": {
    "default": 8,
    "kind": "int"
  },
  "workspace": {
    "default": null,
    "kind": "float"
  }
} as const;
