#!/bin/sh
# Copy every object out of the running SeaweedFS into RustFS, then verify.
#
# Run this on a host whose `objectstore` is still SeaweedFS, after pulling the
# commit that switched docker-compose.yml to RustFS but BEFORE `./up.sh up`:
# that `up` is the cutover, and it starts RustFS on ../data/rustfs, which is
# exactly the directory this script fills.
#
# The source is the existing objectstore container, reached as objectstore:9000
# on the internal network. The target is a temporary `rustfs-new` service with
# the production image and settings, writing to ../data/rustfs. It is stopped
# again before this script exits, because two RustFS processes must never
# share a data directory and the real objectstore is about to take it over.
#
# Safety:
#   - SeaweedFS is only ever read. Nothing here deletes, moves or rewrites a
#     source object, and ../data/seaweedfs is left as it is: it is the way back.
#   - Re-runnable: objects already on the target with the same SHA-256 are
#     skipped, so an interrupted copy can simply be run again, and the final
#     pass with writers stopped only moves what changed in between.
#   - Non-destructive on failure: it exits non-zero and cuts nothing over.
#
# Usage, from deploy/:
#   ./migrate-seaweedfs-to-rustfs.sh            # copy + verify
#   ./migrate-seaweedfs-to-rustfs.sh --verify   # verify only, copy nothing
#   ./migrate-seaweedfs-to-rustfs.sh --dry-run  # list what would be copied
set -eu
cd "$(dirname "$0")"

PROJECT_NAME=ikg-studio-model-training-platform
MODE=copy
case "${1:-}" in
--verify) MODE=verify ;;
--dry-run) MODE=dryrun ;;
"") ;;
*)
  echo "usage: $0 [--verify|--dry-run]" >&2
  exit 2
  ;;
esac

[ -f .env ] || {
  echo "migrate: deploy/.env not found" >&2
  exit 1
}

# Read values out of .env rather than sourcing it: the file is Compose's env
# format, not shell (DATA_ROOT holds comma-separated paths), so `. ./.env`
# breaks. up.sh reads it the same way for the same reason.
envval() {
  grep -E "^$1=" .env 2>/dev/null | tail -1 | cut -d= -f2- | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"
}

S3_ACCESS_KEY=$(envval S3_ACCESS_KEY)
S3_SECRET_KEY=$(envval S3_SECRET_KEY)
PG_USER=$(envval POSTGRES_MIGRATION_USER)
PG_DB=$(envval POSTGRES_DB)
[ -n "$S3_ACCESS_KEY" ] && [ -n "$S3_SECRET_KEY" ] || {
  echo "migrate: S3_ACCESS_KEY/S3_SECRET_KEY not set in deploy/.env" >&2
  exit 1
}

# Both sides use the same keys, so the cutover changes no service's config.
compose() {
  docker compose --project-name "$PROJECT_NAME" \
    -f docker-compose.yml -f docker-compose.migration.yml "$@"
}

SOURCE=$(docker ps -q --filter "label=com.docker.compose.project=$PROJECT_NAME" \
  --filter label=com.docker.compose.service=objectstore)
[ -n "$SOURCE" ] || {
  echo "migrate: no running objectstore container in project $PROJECT_NAME" >&2
  exit 1
}
case $(docker inspect -f '{{.Config.Image}}' "$SOURCE") in
*seaweedfs*) ;;
*)
  echo "migrate: the running objectstore is $(docker inspect -f '{{.Config.Image}}' "$SOURCE"), not SeaweedFS." >&2
  echo "migrate: either the cutover already happened or this host never ran SeaweedFS." >&2
  exit 1
  ;;
esac

cat >docker-compose.migration.yml <<'YAML'
# Generated by migrate-seaweedfs-to-rustfs.sh. Temporary: brings RustFS up next
# to the running SeaweedFS so data can be copied between them. Safe to delete
# after the cutover; it is gitignored.
services:
  rustfs-new:
    image: rustfs/rustfs:1.0.1
    restart: "no"
    depends_on:
      objectstore-init: {condition: service_completed_successfully}
    networks: [internal-network]
    volumes:
      - ../data/rustfs:/data
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: "false"
      RUSTFS_OBS_LOGGER_LEVEL: warn
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:9000/health"]
      interval: 5s
      timeout: 5s
      retries: 12
YAML

cleanup() {
  rm -f "${EXPECTED_KEYS:-}"
  # Stopped on every exit, success or not: the real objectstore takes over
  # ../data/rustfs at cutover, and must not share it with this one.
  compose rm -sf rustfs-new >/dev/null 2>&1 || true
}
trap cleanup EXIT
trap 'exit 130' INT TERM

echo "migrate: starting RustFS alongside SeaweedFS…" >&2
# objectstore-init is a dependency and runs first (chown of ../data/rustfs);
# --no-deps would skip it. The running objectstore is not a dependency of
# rustfs-new, so it is left alone.
compose up -d rustfs-new >/dev/null

i=0
until [ "$(compose ps -q rustfs-new | xargs docker inspect -f '{{.State.Health.Status}}' 2>/dev/null)" = healthy ]; do
  i=$((i + 1))
  [ "$i" -gt 60 ] && {
    echo "migrate: RustFS did not become healthy" >&2
    compose logs --tail=30 rustfs-new >&2
    exit 1
  }
  sleep 2
done
echo "migrate: RustFS healthy." >&2

# The copy runs inside the training-worker image: it already has the minio SDK
# this platform uses, so the transfer exercises the same client code.
WORKER_IMAGE=$(docker inspect -f '{{.Config.Image}}' \
  "$(docker ps -aq --filter "label=com.docker.compose.project=$PROJECT_NAME" \
    --filter label=com.docker.compose.service=training-worker | head -1)" 2>/dev/null ||
  echo "${PROJECT_NAME}-training-worker")

# Postgres, not the object store, is the authority on which artifacts must
# exist (AGENTS.md rule 6). Read-only SELECT as the migration role. Tab-
# separated so that a key with a space in it survives.
EXPECTED_KEYS=$(mktemp)
if [ -n "$PG_USER" ] && [ -n "$PG_DB" ]; then
  compose exec -T postgres psql -U "$PG_USER" -d "$PG_DB" -t -A -F "$(printf '\t')" \
    -c "select bucket_name, object_key, checksum from app.artifacts where archived_at is null;" |
    tr -d '\r' | grep -v '^$' >"$EXPECTED_KEYS" || true
  echo "migrate: $(wc -l <"$EXPECTED_KEYS" | tr -d ' ') artifact rows to reconcile against." >&2
else
  echo "migrate: POSTGRES_MIGRATION_USER/POSTGRES_DB absent; DB reconciliation skipped" >&2
fi

set +e
docker run --rm \
  --network "${PROJECT_NAME}_internal-network" \
  -e SRC_ENDPOINT=objectstore:9000 \
  -e SRC_ACCESS_KEY="$S3_ACCESS_KEY" \
  -e SRC_SECRET_KEY="$S3_SECRET_KEY" \
  -e DST_ENDPOINT=rustfs-new:9000 \
  -e DST_ACCESS_KEY="$S3_ACCESS_KEY" \
  -e DST_SECRET_KEY="$S3_SECRET_KEY" \
  -e MODE="$MODE" \
  -e EXPECTED_KEYS_FILE=/expected-keys.tsv \
  -v "$PWD/migrate_objects.py:/migrate_objects.py:ro" \
  -v "$EXPECTED_KEYS:/expected-keys.tsv:ro" \
  "$WORKER_IMAGE" \
  uv run --no-sync python /migrate_objects.py
STATUS=$?
set -e

if [ "$STATUS" -ne 0 ]; then
  echo "migrate: FAILED — SeaweedFS untouched, nothing was cut over." >&2
  exit "$STATUS"
fi
[ "$MODE" = copy ] || exit 0

cat >&2 <<EOF

migrate: data copied and verified. Nothing has been cut over yet; the
application still reads and writes SeaweedFS. To switch:
  1. ./up.sh stop backend scheduler training-worker dataset-worker
  2. ./migrate-seaweedfs-to-rustfs.sh       (again: copies what changed since)
  3. ./up.sh up -d --build                  (objectstore becomes RustFS)
  4. Download an existing artifact and upload a model in the UI.
Keep ../data/seaweedfs until that has run clean for a while; it is the only
way back (see deploy/README.md).
EOF
