#!/bin/sh
# Copy every artifact out of the running MinIO into SeaweedFS, then verify.
#
# Why a script and not `mc mirror`: the mc binary lives inside the MinIO image, which is
# the thing being retired, and mirror reports success on a byte count without proving the
# objects are readable through the new server. This verifies each object end to end
# (key present, size equal, SHA-256 equal) and reconciles against app.artifacts, which is
# the authority on what must exist (AGENTS.md: PostgreSQL is the source of truth).
#
# Safety:
#   - MinIO is only ever read. Nothing here deletes, moves or rewrites a source object.
#   - Re-runnable: objects already present with a matching checksum are skipped, so an
#     interrupted copy can simply be run again.
#   - Non-destructive on failure: it exits non-zero and leaves both stores intact. The
#     cutover is a separate, deliberate step (compose change), never done here.
#
# Usage, from deploy/ with the stack up:
#   ./migrate-minio-to-seaweedfs.sh            # copy + verify
#   ./migrate-minio-to-seaweedfs.sh --verify   # verify only, copy nothing
#   ./migrate-minio-to-seaweedfs.sh --dry-run  # list what would be copied
set -eu
cd "$(dirname "$0")"

PROJECT_NAME=ikg-studio-model-training-platform
MODE=copy
case "${1:-}" in
--verify) MODE=verify ;;
--dry-run) MODE=dryrun ;;
"") ;;
*)
  echo "usage: $0 [--verify|--dry-run]" >&2
  exit 2
  ;;
esac

[ -f .env ] || {
  echo "migrate: deploy/.env not found" >&2
  exit 1
}

# Read values out of .env rather than sourcing it. The file is Compose's env format, not
# shell: DATA_ROOT holds comma-separated paths and nothing is quoted, so `. ./.env` tries
# to execute the second path as a command. up.sh reads it the same way for the same
# reason. Values are taken verbatim after the first '=', with surrounding quotes stripped.
envval() {
  grep -E "^$1=" .env 2>/dev/null | tail -1 | cut -d= -f2- | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"
}

MINIO_ENDPOINT=$(envval MINIO_ENDPOINT)
MINIO_ACCESS_KEY=$(envval MINIO_ACCESS_KEY)
MINIO_SECRET_KEY=$(envval MINIO_SECRET_KEY)
MINIO_BUCKET=$(envval MINIO_BUCKET)
SEAWEEDFS_ACCESS_KEY=$(envval SEAWEEDFS_ACCESS_KEY)
SEAWEEDFS_SECRET_KEY=$(envval SEAWEEDFS_SECRET_KEY)

[ -n "$MINIO_ACCESS_KEY" ] || {
  echo "migrate: MINIO_ACCESS_KEY not set in deploy/.env" >&2
  exit 1
}
[ -n "$MINIO_SECRET_KEY" ] || {
  echo "migrate: MINIO_SECRET_KEY not set in deploy/.env" >&2
  exit 1
}
SRC_BUCKET=${MINIO_BUCKET:-artifacts}
# The new server's credentials default to the existing ones so a cutover does not force
# every service's config to change at the same time as the data moves.
SW_ACCESS_KEY=${SEAWEEDFS_ACCESS_KEY:-$MINIO_ACCESS_KEY}
SW_SECRET_KEY=${SEAWEEDFS_SECRET_KEY:-$MINIO_SECRET_KEY}

compose() {
  docker compose --project-name "$PROJECT_NAME" \
    -f docker-compose.yml -f docker-compose.migration.yml "$@"
}

# The target runs as a temporary service alongside MinIO so both are reachable at once.
# It writes to the same ../data/seaweedfs volume the permanent service will adopt, so the
# copy is not thrown away at cutover.
cat >docker-compose.migration.yml <<'YAML'
# Generated by migrate-minio-to-seaweedfs.sh. Temporary: brings SeaweedFS up next to
# MinIO so data can be copied between them. Safe to delete after the cutover.
services:
  seaweedfs-new:
    image: chrislusf/seaweedfs:3.68
    restart: "no"
    # volumePreallocate=false is the setting that matters for disk: with the default on,
    # every volume file is fully allocated up front, so 840 MiB of artifacts reserved
    # 57 GB of blocks. `du -sb` reports apparent size and hides this entirely; only df
    # or `du -sk` shows it. The flag only affects volumes at creation time, so it has to
    # be set before the copy rather than tuned afterwards.
    #
    # volumeSizeLimitMB stays at the 4096 default on purpose: lowering it below the size
    # the existing volume files were created at makes the master refuse to load them, and
    # the S3 gateway then waits on the filer forever.
    command: >
      server -s3 -dir=/data
      -s3.config=/etc/seaweedfs/s3.json
      -master.volumePreallocate=false
    networks: [internal-network]
    volumes:
      - ../data/seaweedfs:/data
      - ./seaweedfs-s3.generated.json:/etc/seaweedfs/s3.json:ro
    # Two things are version- and auth-specific here, both verified against this exact
    # image rather than assumed:
    #   - wget, not curl: 3.68 ships busybox wget and has no curl at all, so a curl probe
    #     can never succeed even while the S3 API serves normally.
    #   - /status, not /healthz or /: on 3.68 /healthz and / both answer 403 once an
    #     identity file is configured, so they report unhealthy forever. /status answers
    #     200 on loopback and only once the S3 gateway is actually listening.
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8333/status || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
YAML

# Credentials are injected into a generated copy so the committed template never holds a
# secret and the file is not world-readable.
sed -e "s|__S3_ACCESS_KEY__|${SW_ACCESS_KEY}|" \
  -e "s|__S3_SECRET_KEY__|${SW_SECRET_KEY}|" \
  seaweedfs-s3.json >seaweedfs-s3.generated.json
chmod 600 seaweedfs-s3.generated.json

mkdir -p ../data/seaweedfs

echo "migrate: starting SeaweedFS alongside MinIO…" >&2
compose up -d --no-deps seaweedfs-new >/dev/null

# Wait for health rather than sleeping: the S3 gateway accepts connections before it can
# serve, and a premature first PUT fails in a way that looks like an incompatibility.
i=0
until [ "$(compose ps -q seaweedfs-new | xargs -r docker inspect -f '{{.State.Health.Status}}' 2>/dev/null)" = healthy ]; do
  i=$((i + 1))
  [ "$i" -gt 60 ] && {
    echo "migrate: SeaweedFS did not become healthy" >&2
    compose logs --tail=30 seaweedfs-new >&2
    exit 1
  }
  sleep 2
done
echo "migrate: SeaweedFS healthy." >&2

# Create the bucket through the filer rather than over S3. CreateBucket in SeaweedFS
# requires the identity to hold the global "Admin" action, and granting that to the
# credentials the workers use would hand them far more than reading and writing
# artifacts. An S3 bucket here is just a directory under /buckets, so making the
# directory produces exactly the same bucket while the identity keeps Read/Write/List
# only. Idempotent: mkdir of an existing path is not an error.
SW_CONTAINER=$(compose ps -q seaweedfs-new)
docker exec "$SW_CONTAINER" sh -c \
  "echo 'fs.mkdir /buckets/${SRC_BUCKET}' | weed shell -filer=localhost:8888" >/dev/null 2>&1 || true

if ! docker exec "$SW_CONTAINER" sh -c \
  "echo 'fs.ls /buckets' | weed shell -filer=localhost:8888" 2>/dev/null | grep -q "${SRC_BUCKET}"; then
  echo "migrate: could not create bucket '${SRC_BUCKET}' on the target" >&2
  exit 1
fi

# The copy runs inside the training-worker image: it already has the exact minio SDK this
# platform uses, so the transfer exercises the same client code paths as production.
WORKER_IMAGE=$(compose config --images 2>/dev/null | grep -m1 training-worker || echo "${PROJECT_NAME}-training-worker:latest")

# Dump the keys the database expects so the verifier can reconcile against it. Postgres,
# not the object store, is the authority on which artifacts must exist (AGENTS.md rule 6):
# two stores agreeing with each other would still miss an artifact row whose object was
# never uploaded. Read-only SELECT, run as the migration role which can read app tables.
PG_USER=$(envval POSTGRES_MIGRATION_USER)
PG_DB=$(envval POSTGRES_DB)
EXPECTED_KEYS=$(mktemp)
trap 'rm -f "$EXPECTED_KEYS"' EXIT INT TERM
if [ -n "$PG_USER" ] && [ -n "$PG_DB" ]; then
  compose exec -T postgres psql -U "$PG_USER" -d "$PG_DB" -t -A -F' ' \
    -c "select bucket_name, object_key from app.artifacts where archived_at is null;" \
    2>/dev/null | tr -d '\r' | grep -v '^$' >"$EXPECTED_KEYS" || true
  echo "migrate: $(wc -l <"$EXPECTED_KEYS" | tr -d ' ') artifact rows to reconcile against." >&2
else
  echo "migrate: POSTGRES_MIGRATION_USER/POSTGRES_DB absent; DB reconciliation skipped" >&2
fi

docker run --rm \
  --network "${PROJECT_NAME}_internal-network" \
  -e SRC_ENDPOINT="${MINIO_ENDPOINT:-minio:9000}" \
  -e SRC_ACCESS_KEY="$MINIO_ACCESS_KEY" \
  -e SRC_SECRET_KEY="$MINIO_SECRET_KEY" \
  -e SRC_BUCKET="$SRC_BUCKET" \
  -e DST_ENDPOINT="seaweedfs-new:8333" \
  -e DST_ACCESS_KEY="$SW_ACCESS_KEY" \
  -e DST_SECRET_KEY="$SW_SECRET_KEY" \
  -e MODE="$MODE" \
  -e EXPECTED_KEYS_FILE=/expected-keys.txt \
  -v "$PWD/migrate_objects.py:/migrate_objects.py:ro" \
  -v "$EXPECTED_KEYS:/expected-keys.txt:ro" \
  "$WORKER_IMAGE" \
  uv run --no-sync python /migrate_objects.py
STATUS=$?

if [ "$STATUS" -ne 0 ]; then
  echo "migrate: FAILED — both stores left untouched, nothing was cut over." >&2
  exit "$STATUS"
fi

cat >&2 <<EOF

migrate: data copied and verified.

Nothing has been cut over yet; the application still reads and writes MinIO. To switch:
  1. Replace the minio service in docker-compose.yml with the seaweedfs service
     (see deploy/README.md), keeping MINIO_* variable names so no app config changes.
  2. ./up.sh up -d --force-recreate backend training-worker dataset-worker
  3. Exercise an upload and a download, then re-run this script with --verify.
  4. Keep ../data/minio and the saved MinIO image until that has run clean for a while;
     that directory is the only copy of the old artifacts.
EOF
